name: CI-CD Docker & Render

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t bryant10/entrega-continua:${{ github.sha }} .

      - name: Push Docker image
        run: docker push bryant10/entrega-continua:${{ github.sha }}

  deploy-to-render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d2gkk7ndiees73dk7kh0" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
